import { JOB } from "../domain/job.types";

export const data: JOB[] = [
  {
    id: "1",
    title: "Software Engineer",
    location: "New York, NY",
    candidatesApplied: 42,
    recruiter: "John Smith",
    department: "Engineering",
    status: "Active",
    postedDate: "2024-01-15T09:30:00",
  },
  {
    id: "2",
    title: "Product Manager",
    location: "San Francisco, CA",
    candidatesApplied: 30,
    recruiter: "Sarah Johnson",
    department: "Product",
    status: "Active",
    postedDate: "2024-01-20T14:15:00",
  },
  {
    id: "3",
    title: "UI/UX Designer",
    location: "Remote",
    candidatesApplied: 18,
    recruiter: "Mike Davis",
    department: "Design",
    status: "Inactive",
    postedDate: "2024-01-10T11:00:00",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    location: "Boston, MA",
    candidatesApplied: 26,
    recruiter: "Emily Chen",
    department: "Engineering",
    status: "Active",
    postedDate: "2024-02-02T10:45:00",
  },
  {
    id: "5",
    title: "Data Analyst",
    location: "Chicago, IL",
    candidatesApplied: 14,
    recruiter: "David Wilson",
    department: "Data",
    status: "Active",
    postedDate: "2024-02-08T16:20:00",
  },
  {
    id: "6",
    title: "HR Manager",
    location: "Austin, TX",
    candidatesApplied: 22,
    recruiter: "Lisa Anderson",
    department: "Human Resources",
    status: "Inactive",
    postedDate: "2024-01-28T13:30:00",
  },
  {
    id: "7",
    title: "Marketing Specialist",
    location: "Remote",
    candidatesApplied: 11,
    recruiter: "Tom Martinez",
    department: "Marketing",
    status: "Inactive",
    postedDate: "2024-02-01T08:00:00",
  },
  {
    id: "8",
    title: "QA Engineer",
    location: "Seattle, WA",
    candidatesApplied: 33,
    recruiter: "Rachel Brown",
    department: "Engineering",
    status: "Active",
    postedDate: "2024-01-18T15:45:00",
  },
  {
    id: "9",
    title: "Business Analyst",
    location: "Miami, FL",
    candidatesApplied: 27,
    recruiter: "Kevin Lee",
    department: "Business",
    status: "Active",
    postedDate: "2024-02-10T12:00:00",
  },
  {
    id: "10",
    title: "Customer",
    location: "Denver, CO",
    candidatesApplied: 9,
    recruiter: "Amanda Taylor",
    department: "Support",
    status: "Inactive",
    postedDate: "2024-01-22T09:15:00",
  },
];
